name: Deploy infrastructure

on:
  repository_dispatch:
    types:
      - deploy
  workflow_dispatch:
    inputs:
      environment:
        description: Environment to deploy to.
        default: aws-prod
        required: true
        type: environment
      config:
        description: The OpenTofu configuration to plan.
        required: true
        type: choice
        options:
          - backend
          - ctc.demo.getyourrefund.org
          - ctc.staging.getyourrefund.org
          - datadog
          - demo.fileyourstatetaxes.org
          - demo.getyourrefund.org
          - demo.mireembolso.org
          - staging.fileyourstatetaxes.org
          - staging.getyourrefund.org
          - staging.mireembolso.org
          - staging.pya.fileyourstatetaxes.org
          - pya.fileyourstatetaxes.org
          - www.fileyourstatetaxes.org
          - www.getctc.org
          - www.getyourrefund.org
          - www.mireembolso.org
env:
  CONFIG: ${{ inputs.config || github.event.client_payload.config }}

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy ${{ inputs.config }} to ${{ inputs.environment }}
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment || github.event.client_payload.environment }}
    env:
      APTIBLE_USERNAME: ${{ secrets.APTIBLE_USERNAME }}
      APTIBLE_PASSWORD: ${{ secrets.APTIBLE_PASSWORD }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Setup OpenTofu
        uses: opentofu/setup-opentofu@v1
      - name: Initialize OpenTofu
        working-directory: ./tofu/config/${{ env.CONFIG }}
        run: tofu init
      # TODO: Add a manual approval step here. For now, we'll use GitHub
      # Actions' environment protection feature for sensitive environments.
      - name: Apply changes
        working-directory: ./tofu/config/${{ env.CONFIG }}
        run: tofu apply --auto-approve
