name: Main Checks

on:
  push:
    branches:
      - main

permissions:
  contents: read
  security-events: write

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      # Required to avoid rate limiting when downloading plugins.
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - uses: actions/cache@v4
        name: Cache plugin directory
        with:
          path: ~/.tflint.d/plugins
          key: tflint-${{ hashFiles('.tflint.hcl') }}
      - uses: terraform-linters/setup-tflint@v4
        name: Setup TFLint
      - name: Show version
        run: tflint --version
      - name: Init TFLint
        run: tflint --init
      # Use a bash script to run tflint on each modified module.
      - name: Run TFLint
        run: tflint --format sarif --recursive --config "$GITHUB_WORKSPACE/.tflint.hcl" > tflint-results.sarif
      - name: Upload SARIF result
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: tflint-results.sarif

  trivy:
    name: trivy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Run Trivy vulnarability scanner
        uses: aquasecurity/trivy-action@0.30.0
        with:
          scan-type: config
          ignore-unfixed: true
          skip-dirs: '**/*/.terraform'
          exit-code: 1
          format: sarif
          output: trivy-results.sarif
      - name: Upload SARIF result
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-results.sarif
